# Generated by Django 3.0.8 on 2020-08-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField()),
                ('task_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], unique=True)),
                ('update_type', models.DateField(default='%d %b, %Y')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
